# Generated by Django 4.2 on 2023-04-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_term", models.DecimalField(decimal_places=2, max_digits=5)),
                ("sencond_term", models.DecimalField(decimal_places=2, max_digits=5)),
                ("sum", models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
